### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by nodgear** [januwA/node-windows-x64#2]
OS: W10pro x64 (20H2)
Python 39
Visual Studio 2017
GYP Error while building from npm

Pastebin with logs: https://pastebin.com/cm3FpiJH

Switched pcs, and now i have this building error.

**Comment by nodgear** [comment]
Updt: The missing header was a bit strange to me, since i had C++ tools, so i reinstalled vstudio and the missing header problem is gone, but i can't build still.

**Comment by nodgear** [comment]
Here's latest log:

@edit: also tried by cloning instead of installing from npc, here's result:
```gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@14.16.1 | win32 | x64
gyp info find Python using Python version 3.9.4 found at "C:\Python39\python.exe"
gyp info find VS using VS2017 (15.9.28307.1500) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Python39\python.exe
gyp info spawn args [
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\teuzh\\git\\node-windows-x64\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\teuzh\\AppData\\Local\\node-gyp\\Cache\\14.16.1\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\teuzh\\AppData\\Local\\node-gyp\\Cache\\14.16.1',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\teuzh\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.16.1\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\teuzh\\git\\node-windows-x64',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\teuzh\\git\\node-windows-x64\\build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Warning: Missing input files:
C:\Users\teuzh\git\node-windows-x64\deps_release\dll\**
gyp info spawn C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe
gyp info spawn args [
gyp info spawn args   'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64'
gyp info spawn args ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Copying C:\Users\teuzh\git\node-windows-x64/deps_release/dll/** to C:\Users\teuzh\git\node-windows-x64/build/Release
  /**
  C:\Users\teuzh\git\node-windows-x64\deps_release\dll\asmjit.dll
  C:\Users\teuzh\git\node-windows-x64\deps_release\dll\asmtk.dll
          2 file(s) copied.
  Copying C:\Users\teuzh\git\node-windows-x64/deps_release/dll/** to C:\Users\teuzh\git\node-windows-x64/build/Release
  /**
  C:\Users\teuzh\git\node-windows-x64\deps_release\dll\asmjit.dll
  C:\Users\teuzh\git\node-windows-x64\deps_release\dll\asmtk.dll
          2 file(s) copied.
  ajanuw.cpp
  va_manage.cpp
  win32_gui.cpp
  main.cpp
c:\users\teuzh\git\node-windows-x64\src\ajanuw.cpp(23): error C2672: 'std::tolower': no matching overloaded function f
ound [C:\Users\teuzh\git\node-windows-x64\build\node-windows-x64.vcxproj]
c:\users\teuzh\git\node-windows-x64\src\ajanuw.cpp(23): error C2780: '_Elem std::tolower(_Elem,const std::locale &)':
expects 2 arguments - 1 provided [C:\Users\teuzh\git\node-windows-x64\build\node-windows-x64.vcxproj]
  c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\locale(274): note: s
  ee declaration of 'std::tolower'
c:\users\teuzh\git\node-windows-x64\src\ajanuw.cpp(34): error C2672: 'std::toupper': no matching overloaded function f
ound [C:\Users\teuzh\git\node-windows-x64\build\node-windows-x64.vcxproj]
c:\users\teuzh\git\node-windows-x64\src\ajanuw.cpp(34): error C2780: '_Elem std::toupper(_Elem,const std::locale &)':
expects 2 arguments - 1 provided [C:\Users\teuzh\git\node-windows-x64\build\node-windows-x64.vcxproj]
  c:\program files (x86)\microsoft visual studio\2017\community\vc\tools\msvc\14.16.27023\include\locale(281): note: s
  ee declaration of 'std::toupper'
c:\users\teuzh\git\node-windows-x64\src\ajanuw.cpp(1555): warning C4530: C++ exception handler used, but unwind semant
ics are not enabled. Specify /EHsc [C:\Users\teuzh\git\node-windows-x64\build\node-windows-x64.vcxproj]
  win_delay_load_hook.cc
c:\users\teuzh\git\node-windows-x64\src\tools.hpp(368): warning C4530: C++ exception handler used, but unwind semantic
s are not enabled. Specify /EHsc (compiling source file ..\src\main.cpp) [C:\Users\teuzh\git\node-windows-x64\build\no
de-windows-x64.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\teuzh\git\node-windows-x64
gyp ERR! node -v v14.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command."```

**Comment by nodgear** [comment]
Edited last message to include my attempt by cloning the repository
I would appreciate any feedback on why it's not building for me, even if it's just closing the issue without any help.

**Comment by januwA** [comment]
I saw an error message
```
gyp ERR! node-gyp -v v5.1.0
```

Upgrade node-gyp,Maybe the error will go away

**Comment by nodgear** [comment]
> 
> 
> I saw an error message
> 
> ```
> gyp ERR! node-gyp -v v5.1.0
> ```
> 
> Upgrade node-gyp,Maybe the error will go away

Found the issue after reading the log multiple times
Could only compile using Visual Studio 2019, i would add that information on the read.me.


Extra: https://github.com/januwA/node-windows-x64/blob/cc0d9be6d0b137206f6daa5506796c8843b89ebd/test/test.ts
That makes the whole event loop stop, basically crashing the electron main process.
Tried using thread workers, but doesn't work properly on child worker..

**Comment by januwA** [comment]
I guess it should be possible to use nodejs to create child threads

test.ts
```ts
import { fork } from "child_process";
import * as path from "path";

const child = fork(path.resolve(__dirname, "child.ts"));

child.on("message", (msg) => {
  console.log(msg);
});
```

child.ts:
```ts
import { node_windows_x64 as nw } from "../";
nw.globalDefine();

let WM_ShellHook = 0;
const wui = new nw.Win32Gui("Node Win32 Gui", "window caption");

if (wui.initRegisterClass() && wui.initWindow()) {
  if (nw["user32.RegisterShellHookWindow"](wui.hwnd)) {
    WM_ShellHook = nw["user32.RegisterWindowMessageA"]("SHELLHOOK");
    if (WM_ShellHook === 0) {
      console.log("RegisterWindowMessageA fail.");
    }
  } else {
    console.log("RegisterShellHookWindow fail.");
  }

  wui.messageLoop((hWnd, message, wParam, lParam) => {
    switch (message) {
      case WM_ShellHook:
        switch (wParam) {
          case HSHELL_WINDOWCREATED:
            process.send("WINDOWCREATED");
            break;

          case HSHELL_WINDOWDESTROYED:
            process.send("WINDOWDESTROYED");
            break;

          case HSHELL_ACTIVATESHELLWINDOW:
            process.send("ACTIVATESHELLWINDOW");
            break;

          default:
            break;
        }
        break;

      default:
        break;
    }
  });
}
```
